services:
  server:
    build:
      context: .
    environment:
      NODE_ENV: production
    ports:
      - 3000:3000

  db:
    image: postgres:17.0
    environment:
      POSTGRES_PASSWORD: robiksrobik
      POSTGRES_DB: FriCapsule
      POSTGRES_USER: Robinnoss
    ports:      
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
    
volumes:
  db-data: